service: smartGardenApi

plugins:
  - serverless-webpack
  # - serverless-domain-manager
  - serverless-prune-plugin
  # - serverless-step-functions
  - serverless-plugin-split-stacks
  - serverless-pseudo-parameters

custom:
  stage: ${opt:stage, self:provider.stage}
  memorySize:
    dev: 128
    # staging: 128
    # production: 128
  # host:
  #   dev: app-dev.smartgarden.tk
  #   staging: staging.smartgarden.tk
  #   production: app.smartgarden.tk
  webpack:
      webpackConfig: './webpack.config.js'
      includeModules: true
    # customDomain:
    #   domainName: api.smartgarden.tk
    #   basePath: ${self:custom.stage}
    #   stage: ${self:custom.stage}
    #   createRoute53Record: true
    #   certificateName: '*.smartgarden.tk'
  prune:
    automatic: true
    number: 20
  baseFunctionName: arn:aws:lambda:us-east-1:514777035509:function:${self:service}-${self:custom.stage}-
  splitStacks:
    perFunction: false
    perType: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  profile: smartGarden
  memorySize: ${self:custom.memorySize.${self:custom.stage}}
  versionFunctions: false
  environment:
    serviceName: ${self:service}
    region: ${self:provider.region}
    stage: ${self:custom.stage}
    # host: ${self:custom.host.${self:custom.stage}}
    baseFunctionName: ${self:custom.baseFunctionName}
    dynamodbMeasureTable: ${self:service}-${self:custom.stage}-measures

package:
  individually: true
  exclude:
    - .serverless/**
    - .git/**
    - node_modules/**

functions:
  DeviceTopicListener:
    handler: src/functions/device.deviceTopicListener
    iamRoleStatementsName: ${self:service}-${self:custom.stage}-DTL-lambdaRole
    # iamRoleStatements:
    #   - Effect: Allow]
    #     Action: dynamodb:*
    #     Resource: arn:aws:dynamodb:${self:provider.region}:514777035509:table/${self:provider.environment.dynamodbSourcesTable}

resources:
  # DYNAMO MEASURES TABLE
  - ${file(resources/dynamoMeasureTable.yml)}
