Resources:
  dynamodbDeviceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.dynamodbDeviceTable}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: N
        - AttributeName: gardenId
          AttributeType: N
        - AttributeName: gardenerId
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: GardenId
          KeySchema:
            - AttributeName: gardenId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: GardenerId
          KeySchema:
            - AttributeName: gardenerId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
