Resources:
  dynamodbMeasureTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.dynamodbMeasureTable}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: measuredAt
          AttributeType: S
        - AttributeName: sensor
          AttributeType: S
        - AttributeName: plantId
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: Sensor
          KeySchema:
            - AttributeName: sensor
              KeyType: HASH
            - AttributeName: measuredAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: PlantId
          KeySchema:
            - AttributeName: plantId
              KeyType: HASH
            - AttributeName: measuredAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
